#!/usr/bin/env sh

origdir=`pwd`
scriptdir=`dirname $0`
if [ "$scriptdir" != "scripts" ]; then
   origdir=`dirname $origdir`
fi

#
# Select or create ThirdParty library directory
#

default_libdir="`dirname $origdir`/Mtk_thirdparty"
/bin/echo -n "Enter thirdparty library tarball directory ($default_libdir): "
read libdir
if [ ! "$libdir" ]; then
    libdir=$default_libdir
fi
if [ ! -d "$libdir" ]; then
    /bin/echo "Thirdparty library tarball directory does not exist."
    /bin/echo -n "Do you want to create it (y/n)? "
    read ans
    if [ "$ans" = "y" -o "$ans" = "Y" ]; then
	mkdir $libdir
    else
	exit 1
    fi
fi

#
# Download ThirdParty libraries
#

cd $libdir
curl -O ftp://edhs1.gsfc.nasa.gov/edhs/hdfeos/previous_releases/zlib-1.2.5.tar.gz --disable-epsv
curl -O ftp://edhs1.gsfc.nasa.gov/edhs/hdfeos/previous_releases/jpegsrc.v6b.tar.gz --disable-epsv
# curl -O http://www.hdfgroup.org/ftp/HDF/HDF_Current/src/hdf-4.2.8.tar.gz
curl -O http://www.hdfgroup.org/ftp/HDF/releases/HDF4.2.8/src/hdf-4.2.8.tar.gz
curl -O ftp://edhs1.gsfc.nasa.gov/edhs/hdfeos/previous_releases/HDF-EOS2.18v1.00.tar.Z --disable-epsv
