#ifndef MISRERROR_H
#define MISRERROR_H

#include <stdio.h>

typedef enum MTKt_boolean {       /* Boolean type */
  MTK_FALSE = 0,
  MTK_TRUE
} MTKt_boolean;

typedef enum MTKt_status {        /* Return status type */                   
  MTK_SUCCESS = 0,                /* Return codes */
  MTK_FAILURE,
  MTK_OUTBOUNDS,
  MTK_BAD_ARGUMENT,
  MTK_NOT_FOUND,
  MTK_FILE_NOT_FOUND,
  MTK_FILE_OPEN,
  MTK_NULLPTR,
  MTK_DIMENSION_MISMATCH,
  MTK_DATATYPE_MISMATCH,
  MTK_MALLOC_FAILED,
  MTK_CALLOC_FAILED,
  MTK_REALLOC_FAILED,
  MTK_GCTP_FORWARD_INIT_FAILED,
  MTK_GCTP_INVERSE_INIT_FAILED,
  MTK_GCTP_FORWARD_PROJ_FAILED,
  MTK_GCTP_INVERSE_PROJ_FAILED,
  MTK_MISR_PROJ_INIT_FAILED,
  MTK_MISR_FORWARD_PROJ_FAILED,
  MTK_MISR_INVERSE_PROJ_FAILED,
  MTK_HDF_OPEN_FAILED,
  MTK_HDF_ATTACH_FAILED,
  MTK_HDF_SDSTART_FAILED,
  MTK_HDF_SDEND_FAILED,
  MTK_HDF_SDFILEINFO_FAILED,
  MTK_HDF_SDFINDATTR_FAILED,
  MTK_HDF_SDREADATTR_FAILED,
  MTK_HDF_SDATTRINFO_FAILED,
  MTK_HDF_HDFCLOSE_FAILED,
  MTK_HDF_HDFOPEN_FAILED,
  MTK_HDF_VEND_FAILED,
  MTK_HDF_VFFIELDORDER_FAILED,
  MTK_HDF_VFFIELDTYPE_FAILED,
  MTK_HDF_VFNFIELDS_FAILED,
  MTK_HDF_VSATTACH_FAILED,
  MTK_HDF_VSDETACH_FAILED,
  MTK_HDF_VSELTS_FAILED,
  MTK_HDF_VSFIND_FAILED,
  MTK_HDF_VSFINDEX_FAILED,
  MTK_HDF_VSGETFIELDS_FAILED,
  MTK_HDF_VSGETNAME_FAILED,
  MTK_HDF_VSREAD_FAILED,
  MTK_HDF_VSSETFIELDS_FAILED,
  MTK_HDF_VSSIZEOF_FAILED,
  MTK_HDF_VSTART_FAILED,
  MTK_HDFEOS_GDOPEN_FAILED,
  MTK_HDFEOS_GDCLOSE_FAILED,
  MTK_HDFEOS_GDATTACH_FAILED,
  MTK_HDFEOS_GDDETACH_FAILED,
  MTK_HDFEOS_GDINQATTRS_FAILED,
  MTK_HDFEOS_GDINQGRID_FAILED,
  MTK_HDFEOS_GDINQFIELDS_FAILED,
  MTK_HDFEOS_GDNENTRIES_FAILED,
  MTK_HDFEOS_GDREADATTR_FAILED,
  MTK_HDFEOS_GDATTRINFO_FAILED,
  MTK_HDFEOS_GDFIELDINFO_FAILED,
  MTK_HDFEOS_GDDIMINFO_FAILED,
  MTK_HDFEOS_GDREADFIELD_FAILED,
  MTK_HDFEOS_GDGETFILLVALUE_FAILED,
  MTK_HDFEOS_GDPROJINFO_FAILED,
  MTK_HDFEOS_GDGRIDINFO_FAILED,
  MTK_HDFEOS_EHIDINFO_FAILED,
  MTK_NETCDF_OPEN_FAILED,
  MTK_NETCDF_READ_FAILED,
  MTK_NETCDF_CLOSE_FAILED,
  MTK_FILETYPE_NOT_SUPPORTED,
  MTK_DATATYPE_NOT_SUPPORTED,
  MTK_INVALID_FILE,
  MTK_INVALID_GRID,
  MTK_INVALID_FIELD,
  MTK_INVALID_FIELD_DIMENSION,
  MTK_MISSING_FIELD_DIMENSION,
  MTK_EXTRA_FIELD_DIMENSION,
  MTK_DIV_BY_ZERO,
  MTK_INVALID_ERROR_CODE
} MTKt_status;

/* Mtk Error descriptions */

#define MTK_ERR_DESC { \
  "SUCCESS", \
  "FAILURE", \
  "OUT OF BOUNDS", \
  "BAD ARGUMENT", \
  "NOT FOUND", \
  "FILE NOT FOUND", \
  "FILE OPEN FAILED", \
  "NULL POINTER", \
  "DIMENSION MISMATCH", \
  "DATATYPE MISMATCH", \
  "MALLOC FAILED", \
  "CALLOC FAILED", \
  "REALLOC FAILED", \
  "GCTP FORWARD INIT FAILED", \
  "GCTP INVERSE INIT FAILED", \
  "GCTP FORWARD PROJ FAILED", \
  "GCTP INVERSE PROJ FAILED", \
  "MISR PROJECTION INIT FAILED", \
  "MISR FORWARD PROJECTION FAILED", \
  "MISR INVERSE PROJECTION FAILED", \
  "HDF OPEN FAILED", \
  "HDF ATTACH FAILED", \
  "HDF SDSTART FAILED", \
  "HDF SDEND FAILED", \
  "HDF SDFILEINFO FAILED", \
  "HDF SDFINDATTR FAILED", \
  "HDF SDREADATTR FAILED", \
  "HDF SDATTRINFO FAILED", \
  "HDF HDFCLOSE FAILED", \
  "HDF HDFOPEN FAILED", \
  "HDF VEND FAILED", \
  "HDF VFFIELDORDER FAILED", \
  "HDF VFFIELDTYPE FAILED", \
  "HDF VFNFIELDS FAILED", \
  "HDF VSATTACH FAILED", \
  "HDF VSDETACH FAILED", \
  "HDF VSELTS FAILED", \
  "HDF VSFIND FAILED", \
  "HDF VSFINDEX FAILED", \
  "HDF VSGETFIELDS FAILED", \
  "HDF VSGETNAME FAILED", \
  "HDF VSREAD FAILED", \
  "HDF VSSETFIELDS FAILED", \
  "HDF VSSIZEOF FAILED", \
  "HDF VSTART FAILED", \
  "HDFEOS GDOPEN FAILED", \
  "HDFEOS GDCLOSE FAILED", \
  "HDFEOS GDATTACH FAILED", \
  "HDFEOS GDDETACH FAILED", \
  "HDFEOS GDINQATTRS FAILED", \
  "HDFEOS GDINQGRID FAILED", \
  "HDFEOS GDINQFIELDS FAILED", \
  "HDFEOS GDNENTRIES FAILED", \
  "HDFEOS GDREADATTR FAILED", \
  "HDFEOS GDATTRINFO FAILED", \
  "HDFEOS GDFIELDINFO FAILED", \
  "HDFEOS GDDIMINFO FAILED", \
  "HDFEOS GDREADFIELD FAILED", \
  "HDFEOS GDGETFILLVALUE FAILED", \
  "HDFEOS GDPROJINFO FAILED", \
  "HDFEOS GDGRIDINFO FAILED", \
  "HDFEOS EHIDINFO FAILED", \
  "NETCDF OPEN FAILED", \
  "NETCDF READ FAILED", \
  "NETCDF CLOSE FAILED", \
  "FILETYPE NOT SUPPORTED", \
  "DATATYPE NOT SUPPORTED", \
  "INVALID FILE", \
  "INVALID GRID", \
  "INVALID FIELD", \
  "INVALID FIELD DIMENSION", \
  "MISSING FIELD DIMENSION", \
  "EXTRA FIELD DIMENSION", \
  "DIVIDE BY ZERO", \
  "INVALID ERROR CODE" \
}

#define MTK_ERR_MSG_JUMP(msg) \
   { \
      fprintf(stderr,"Error: %s\n",msg); \
      goto ERROR_HANDLE; \
   }

#define MTK_ERR_CODE_JUMP(code) \
   { \
      status_code = code; \
      goto ERROR_HANDLE; \
   }

#define MTK_ERR_CODE_MSG_JUMP(code,msg)		\
  {						\
    fprintf(stderr,"Error: %s\n",msg);		\
    status_code = code;				\
    goto ERROR_HANDLE;				\
  }

#define MTK_ERR_COND_JUMP(code) \
   if (code != MTK_SUCCESS) \
   { \
      status_code = code; \
      goto ERROR_HANDLE; \
   }

#define MTK_PRINT_STATUS(n,v) { \
 printf("%s", v); \
 fflush(stdout); \
 n += sizeof(v) - 1;\
}

#define MTK_PRINT_RESULT(n,v) { \
 int i; \
 for(i=0; i < 55-n; i++) printf(" "); \
 printf("%s\n", v); \
}

#endif /* MISRERROR_H */
